site_name: fil-compute
site_description: Compute-to-data on PDP/Filecoin
site_url: https://Abhay-2811.github.io/fil-compute/
repo_name: fil-compute

theme:
  name: material
  features:
    - navigation.sections
    - navigation.top
    - content.code.copy

nav:
  - Home: index.md
  - Quickstart: 04-quickstart.md
  - Architecture: 02-architecture.md
  - Storage Modes: 05-storage-modes.md
  - Use Cases and Future: 06-limits-and-roadmap.md

markdown_extensions:
  - admonition
  - tables
  - toc:
      permalink: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra_javascript:
  - https://unpkg.com/mermaid@10/dist/mermaid.min.js
  - javascripts/mermaid-init.js
